// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-HMVlJK8kTcTR_lj9bYeKk08Gj8UEcE4',
    appId: '1:557172504707:web:3ae9535f48bc6244f343b6',
    messagingSenderId: '557172504707',
    projectId: 'chaltiforme',
    authDomain: 'chaltiforme.firebaseapp.com',
    storageBucket: 'chaltiforme.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTSIVT9bXHlxiX02ZGhEOoX2E1jx1bVHU',
    appId: '1:557172504707:android:cd5583b746a485f7f343b6',
    messagingSenderId: '557172504707',
    projectId: 'chaltiforme',
    storageBucket: 'chaltiforme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMczNhRqCXENWs_84dYpTcCAwwCKSlb74',
    appId: '1:557172504707:ios:92a246c5e56a5c00f343b6',
    messagingSenderId: '557172504707',
    projectId: 'chaltiforme',
    storageBucket: 'chaltiforme.appspot.com',
    iosBundleId: 'com.example.flutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMczNhRqCXENWs_84dYpTcCAwwCKSlb74',
    appId: '1:557172504707:ios:8b9fc387c39a150cf343b6',
    messagingSenderId: '557172504707',
    projectId: 'chaltiforme',
    storageBucket: 'chaltiforme.appspot.com',
    iosBundleId: 'com.example.flutterapp.RunnerTests',
  );
}
